version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    # Эти свойства перегружают соответствующие в application.yml
    environment:
      - SPRING_SQL_INIT_SCHEMA_LOCATIONS=classpath:schema.sql
    networks:
      - nw
networks:
  nw: