ALTER TABLE IF EXISTS carts
    DROP CONSTRAINT IF EXISTS cart_user_fk;
ALTER TABLE IF EXISTS carts_products
    DROP CONSTRAINT IF EXISTS carts_products_product_fk;
ALTER TABLE IF EXISTS carts_products
    DROP CONSTRAINT IF EXISTS carts_products_cart_fk;
ALTER TABLE IF EXISTS orders
    DROP CONSTRAINT IF EXISTS orders_users_fk;
ALTER TABLE IF EXISTS products_categories
    DROP CONSTRAINT IF EXISTS products_categories_category_fk;
ALTER TABLE IF EXISTS products_categories
    DROP CONSTRAINT IF EXISTS products_categories_product_fk;

DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS carts_products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS orders_details CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS products_categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP SEQUENCE IF EXISTS hibernate_sequence;
CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

DROP SEQUENCE IF EXISTS users_id_seq;
CREATE SEQUENCE users_id_seq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE IF EXISTS products_id_seq;
CREATE SEQUENCE products_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE carts
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT
);
CREATE TABLE carts_products
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT NOT NULL,
    product_id BIGINT NOT NULL
);
CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    name        VARCHAR(255)
);
CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp,
    description VARCHAR(255),
    status      VARCHAR(255),
    total_price numeric(19, 2),
    updated_at  timestamp,
    user_id     BIGINT
);
CREATE TABLE products
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR(255),
    is_available boolean default true,
    name         VARCHAR(255),
    price        numeric(19, 2)
);
CREATE TABLE products_categories
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL,
    category_id BIGINT NOT NULL
);
CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(255) UNIQUE,
    is_active boolean default true,
    name      VARCHAR(255),
    password  VARCHAR(255),
    role      VARCHAR(255)
);
CREATE TABLE orders_details
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_amount     numeric(19, 2),
    product_price      numeric(19, 2)
);

ALTER TABLE IF EXISTS carts
    ADD CONSTRAINT cart_user_fk FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE IF EXISTS carts_products
    ADD CONSTRAINT carts_products_product_fk FOREIGN KEY (product_id) REFERENCES products;
ALTER TABLE IF EXISTS carts_products
    ADD CONSTRAINT carts_products_cart_fk FOREIGN KEY (cart_id) REFERENCES carts;
ALTER TABLE IF EXISTS orders
    ADD CONSTRAINT orders_users_fk FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE IF EXISTS products_categories
    ADD CONSTRAINT products_categories_category_fk
        FOREIGN KEY (category_id) REFERENCES categories;
ALTER TABLE IF EXISTS products_categories
    ADD CONSTRAINT products_categories_product_fk
        FOREIGN KEY (product_id) REFERENCES products;
ALTER TABLE IF EXISTS orders_details
    ADD CONSTRAINT orders_details_order_fk FOREIGN KEY (order_id) REFERENCES orders;
ALTER TABLE IF EXISTS orders_details
    ADD CONSTRAINT orders_details_product_fk FOREIGN KEY (product_id) REFERENCES products;






